version: 2
jobs:
   build:
     docker:
       - image: danteev/texlive
     steps:
       - checkout
       - run: make
       - store_artifacts:
           path: archive/
            run: git add -a
            run: git commit -m "built and uploaded by CI"
            run: git push
