version: 2
jobs:
   build:
     docker:
       - image: danteev/texlive
     steps:
       - checkout
       - run: make
       - deploy:
          name: circleCI build
          command: |
            git config user.email "lukas@digitales-altertum.de"		
            git config user.name "Lukas C. Bossert"		
            git add .
            git commit -m "built by circleCI"
	   - store_artifacts:
          path: build/