version: 2
jobs:
   build:
     docker:
       - image: danteev/texlive
     steps:
       - checkout
       - run: make
       - deploy:
          name: circleCI build
          command:
            git add .
            git commit -m "built by circleCI"
            # Push quietly to prevent showing the token in log
            git push -q
