version: 2
jobs:
   build:
     docker:
       - image: danteev/texlive
     steps:
       - checkout
       - run: make
       - deploy:
          name: CircleCI build
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "lukas@digitales-altertum.de"
            git config user.name "Deployment Bot"
            git add .
            git commit --allow-empty -m "Trigger deployment"
            # Push quietly to prevent showing the token in log
            git push -q
